### ISSUE TITLE
Error: Cannot find module './pubsuffix-psl'

### ISSUE THREAD

**Issue by gokaybiz** [williampayne23/emotional_support_bot#2]
https://github.com/williampayne23/emotional_support_bot/blob/962c9a3e7f6514f082e74cc5cc798d6da42f7681/node_modules/tough-cookie/lib/cookie.js#L35

Outdated, can't install this dependency and throws error.

**Comment by gokaybiz** [comment]
I changed with latest version but now throws
```
internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module './putty'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/opt/lampp/htdocs/nodejs/fbchat/emotional_support_bot/node_modules/sshpk/lib/formats/auto.js:18:13)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/opt/lampp/htdocs/nodejs/fbchat/emotional_support_bot/node_modules/sshpk/lib/private-key.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
```

**Comment by williampayne23** [comment]
Have you been able to install all the dependencies?

**Comment by williampayne23** [comment]
Currently working on my machine.

**Comment by gokaybiz** [comment]
I removed everything and tried reinstall. But after npm install command, still throws './pubsuffix-psl' error.

**Comment by gokaybiz** [comment]
I removed node_modules folder and `npm install --no-bin-links` solved issue
